import json

with open('crack_detection_ResNet50_tf_fixed.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

NEW_CELL24 = [
    "# =============================================================\n",
    "# INFERENSI GAMBAR CUSTOM MENGGUNAKAN TFLITE\n",
    "# Tidak perlu compile ulang / load Keras model yang berat\n",
    "# Preprocessing: simple resize ke 224x224 (TERBUKTI BENAR)\n",
    "# =============================================================\n",
    "\n",
    "TFLITE_PATH  = 'cracksense_ResNet50.tflite'\n",
    "IMG_SIZE     = (224, 224)\n",
    "CLASS_NAMES  = ['Diagonal', 'Horizontal', 'Vertikal']\n",
    "\n",
    "TEST_IMAGE_PATHS = [\n",
    "    './dataset/test/horizontal_1.png',\n",
    "    './dataset/test/horizontal_2.png',\n",
    "    './dataset/test/horizontal_3.png',\n",
    "    './dataset/test/horizontal_4.png',\n",
    "    './dataset/test/horizontal_5.png',\n",
    "\n",
    "    './dataset/test/vertikal_1.png',\n",
    "    './dataset/test/vertikal_2.png',\n",
    "    './dataset/test/vertikal_3.png',\n",
    "    './dataset/test/vertikal_4.png',\n",
    "    './dataset/test/vertikal_5.png',\n",
    "\n",
    "    './dataset/test/diagonal_1.png',\n",
    "    './dataset/test/diagonal_2.png',\n",
    "]\n",
    "\n",
    "\n",
    "# ----------------------------------------------------------\n",
    "# Load TFLite interpreter\n",
    "# ----------------------------------------------------------\n",
    "print(f'Loading TFLite model: {TFLITE_PATH}')\n",
    "interpreter = tf.lite.Interpreter(model_path=TFLITE_PATH)\n",
    "interpreter.allocate_tensors()\n",
    "\n",
    "input_details  = interpreter.get_input_details()\n",
    "output_details = interpreter.get_output_details()\n",
    "\n",
    "print(f'  Input  : shape={input_details[0][\"shape\"]}, dtype={input_details[0][\"dtype\"]}')\n",
    "print(f'  Output : shape={output_details[0][\"shape\"]}, dtype={output_details[0][\"dtype\"]}')\n",
    "print()\n",
    "\n",
    "\n",
    "# ----------------------------------------------------------\n",
    "# Fungsi preprocessing: simple resize ke 224x224\n",
    "# PENTING: jangan pakai center_crop! (penyebab bug Vertikal semua)\n",
    "# ----------------------------------------------------------\n",
    "def preprocess_image_tflite(img_path):\n",
    "    \"\"\"\n",
    "    Load & preprocess gambar untuk TFLite inference.\n",
    "    \n",
    "    Gunakan simple resize ke (224,224) + ResNet preprocessing.\n",
    "    JANGAN pakai preserve_aspect + center_crop (bug: semua jadi Vertikal).\n",
    "    \"\"\"\n",
    "    img_raw = tf.io.read_file(img_path)\n",
    "    img = tf.image.decode_image(img_raw, channels=3, expand_animations=False)\n",
    "    img = tf.cast(img, tf.float32)\n",
    "    # Simple resize langsung ke 224x224\n",
    "    img = tf.image.resize(img, IMG_SIZE)\n",
    "    # ResNet50 preprocessing (mean subtraction BGR)\n",
    "    img = tf.keras.applications.resnet.preprocess_input(img)\n",
    "    # Tambah batch dimension & pastikan float32\n",
    "    img = tf.expand_dims(img, axis=0)\n",
    "    return img.numpy().astype(np.float32)\n",
    "\n",
    "\n",
    "# ----------------------------------------------------------\n",
    "# Fungsi prediksi TFLite (dengan TTA opsional)\n",
    "# ----------------------------------------------------------\n",
    "def tflite_predict_single(img_np):\n",
    "    \"\"\"Jalankan satu prediksi TFLite pada input numpy array.\"\"\"\n",
    "    interpreter.set_tensor(input_details[0]['index'], img_np)\n",
    "    interpreter.invoke()\n",
    "    output = interpreter.get_tensor(output_details[0]['index'])\n",
    "    return output[0]   # shape: (3,)\n",
    "\n",
    "\n",
    "def tflite_predict_with_tta(img_path):\n",
    "    \"\"\"\n",
    "    Prediksi TFLite dengan Test-Time Augmentation (TTA).\n",
    "    Rata-ratakan prediksi dari 4 orientasi gambar.\n",
    "    \"\"\"\n",
    "    img_raw = tf.io.read_file(img_path)\n",
    "    img = tf.image.decode_image(img_raw, channels=3, expand_animations=False)\n",
    "    img = tf.cast(img, tf.float32)\n",
    "    img_resized = tf.image.resize(img, IMG_SIZE)\n",
    "\n",
    "    variants = [\n",
    "        img_resized,\n",
    "        tf.image.flip_left_right(img_resized),   # flip horizontal\n",
    "        tf.image.flip_up_down(img_resized),       # flip vertikal\n",
    "        tf.image.rot90(img_resized, k=1),         # rotasi 90\n",
    "    ]\n",
    "\n",
    "    preds_all = []\n",
    "    for v in variants:\n",
    "        v_norm = tf.keras.applications.resnet.preprocess_input(v)\n",
    "        v_np   = tf.expand_dims(v_norm, 0).numpy().astype(np.float32)\n",
    "        p = tflite_predict_single(v_np)\n",
    "        preds_all.append(p)\n",
    "\n",
    "    return np.mean(preds_all, axis=0)\n",
    "\n",
    "\n",
    "# ----------------------------------------------------------\n",
    "# Fungsi utama: prediksi gambar custom\n",
    "# ----------------------------------------------------------\n",
    "def predict_custom_images_tflite(image_paths, use_tta=True):\n",
    "    results = []\n",
    "\n",
    "    for test_image_path in image_paths:\n",
    "        print(f'\\n=== Uji Gambar: {test_image_path} ===')\n",
    "\n",
    "        if not os.path.exists(test_image_path):\n",
    "            print(f'  [!] File tidak ditemukan!')\n",
    "            results.append({'path': test_image_path, 'prediction': None,\n",
    "                            'confidence': None, 'probabilities': None})\n",
    "            continue\n",
    "\n",
    "        # Load gambar asli untuk tampilan\n",
    "        pil_img = Image.open(test_image_path).convert('RGB')\n",
    "        img_w, img_h = pil_img.size\n",
    "\n",
    "        # Buat tampilan apa yang model terima (simple resize)\n",
    "        img_display = np.array(pil_img.resize(IMG_SIZE[::-1]))\n",
    "\n",
    "        # Tampilkan gambar asli vs input model\n",
    "        fig, axes = plt.subplots(1, 2, figsize=(10, 4))\n",
    "        axes[0].imshow(pil_img)\n",
    "        axes[0].set_title(f'Gambar Asli ({img_w}x{img_h})', fontweight='bold')\n",
    "        axes[0].axis('off')\n",
    "        axes[1].imshow(img_display)\n",
    "        axes[1].set_title(f'Input Model (224x224 resize)', fontweight='bold')\n",
    "        axes[1].axis('off')\n",
    "        plt.suptitle(os.path.basename(test_image_path), fontsize=12, fontweight='bold')\n",
    "        plt.tight_layout()\n",
    "        plt.show()\n",
    "\n",
    "        # Prediksi\n",
    "        if use_tta:\n",
    "            preds  = tflite_predict_with_tta(test_image_path)\n",
    "            metode = 'TFLite + TTA (4 varian orientasi)'\n",
    "        else:\n",
    "            img_np = preprocess_image_tflite(test_image_path)\n",
    "            preds  = tflite_predict_single(img_np)\n",
    "            metode = 'TFLite single inference'\n",
    "\n",
    "        pred_idx   = int(np.argmax(preds))\n",
    "        confidence = float(preds[pred_idx] * 100)\n",
    "        pred_class = CLASS_NAMES[pred_idx]\n",
    "\n",
    "        print(f'  Backend    : TFLite ({TFLITE_PATH})')\n",
    "        print(f'  Metode     : {metode}')\n",
    "        print(f'  Prediksi   : {pred_class}')\n",
    "        print(f'  Keyakinan  : {confidence:.2f}%')\n",
    "        for i, cls in enumerate(CLASS_NAMES):\n",
    "            bar = '|' * int(preds[i] * 40)\n",
    "            print(f'    {cls:12s}: {preds[i]*100:6.2f}% {bar}')\n",
    "\n",
    "        results.append({\n",
    "            'path':          test_image_path,\n",
    "            'prediction':    pred_class,\n",
    "            'confidence':    confidence,\n",
    "            'probabilities': {cls: float(preds[i]*100) for i, cls in enumerate(CLASS_NAMES)}\n",
    "        })\n",
    "\n",
    "    return results\n",
    "\n",
    "\n",
    "# ----------------------------------------------------------\n",
    "# Jalankan prediksi\n",
    "# ----------------------------------------------------------\n",
    "print('=' * 60)\n",
    "print('INFERENSI TFLITE - GAMBAR CUSTOM')\n",
    "print('=' * 60)\n",
    "print(f'Model : {TFLITE_PATH}')\n",
    "print(f'Kelas : {CLASS_NAMES}')\n",
    "print()\n",
    "\n",
    "custom_results = predict_custom_images_tflite(TEST_IMAGE_PATHS, use_tta=True)\n",
    "\n",
    "# Ringkasan\n",
    "print()\n",
    "print('=' * 60)\n",
    "print('RINGKASAN HASIL PREDIKSI')\n",
    "print('=' * 60)\n",
    "for r in custom_results:\n",
    "    if r['prediction'] is not None:\n",
    "        fname = os.path.basename(r['path'])\n",
    "        print(f'  {fname:30s} -> {r[\"prediction\"]:12s} ({r[\"confidence\"]:.1f}%)')\n"
]

# Apply to Cell 24
cell24_src = ''.join(nb['cells'][24]['source'])
if 'predict_custom_images' in cell24_src or 'TEST_IMAGE_PATHS' in cell24_src:
    nb['cells'][24]['source'] = NEW_CELL24
    nb['cells'][24]['outputs'] = []
    nb['cells'][24]['execution_count'] = None
    print("OK: Cell 24 diupdate -> TFLite + simple resize")
else:
    print("SKIP: Cell 24 tidak cocok, cek index cell")

with open('crack_detection_ResNet50_tf_fixed.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Notebook disimpan.")
